name: Deploy Python backend to Azure Web App

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install backend dependencies
        run: pip install -r backend/requirements.txt

      - name: Zip only contents of backend/
        run: |
          cd backend
          zip -r ../release.zip .

      - name: Deploy to Azure
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'nestle-chatbot-api'
          slot-name: 'Production'
          package: release.zip
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
